apiVersion: v1
kind: Service
metadata:
  name: quotes-app-service
spec:
  selector:
    app: quotes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # This should match containerPort in deployment
  type: LoadBalancer