apiVersion: v1
kind: Service
metadata:
  name: quotes-app-service
spec:
  selector:
    app: quotes-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort